global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: 'histogram-test'
    static_configs:
      - targets: ['172.17.0.1:8080'] # use host.docker.internal if on Mac
        labels:
          env: 'test'
